# Generated by Django 4.2.23 on 2025-12-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_alter_ticketimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المدرسة")),
                (
                    "code",
                    models.SlugField(
                        help_text="كود قصير لتمييز المدرسة، يُستخدم في الاختيار والتقارير.",
                        max_length=64,
                        unique=True,
                        verbose_name="المعرّف (code)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة؟")),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط الشعار"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئت في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تم التحديث في"),
                ),
            ],
            options={
                "verbose_name": "مدرسة",
                "verbose_name_plural": "المدارس",
                "ordering": ("name",),
            },
        ),
    ]
