# Generated by Django 4.2.23 on 2025-12-15 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[("teacher", "معلم"), ("manager", "مدير مدرسة")],
                        default="teacher",
                        max_length=16,
                        verbose_name="الدور داخل المدرسة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط؟")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضوية مدرسة",
                "verbose_name_plural": "عضويات المدارس",
                "indexes": [
                    models.Index(
                        fields=["school"], name="reports_sch_school__3592fe_idx"
                    ),
                    models.Index(
                        fields=["teacher"], name="reports_sch_teacher_2eed7d_idx"
                    ),
                ],
                "unique_together": {("school", "teacher", "role_type")},
            },
        ),
    ]
