# Generated by Django 4.2.23 on 2025-12-15 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_schoolmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="reports.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="reports.school",
                verbose_name="المدرسة",
            ),
        ),
    ]
