# Generated by Django 4.2.23 on 2025-12-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_report_school_ticket_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="city",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="المدينة"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="gender",
            field=models.CharField(
                choices=[("boys", "بنين"), ("girls", "بنات")],
                default="boys",
                max_length=8,
                verbose_name="بنين / بنات",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الجوال"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="stage",
            field=models.CharField(
                choices=[
                    ("kg", "رياض أطفال"),
                    ("primary", "ابتدائي"),
                    ("middle", "متوسط"),
                    ("high", "ثانوي"),
                ],
                default="primary",
                max_length=16,
                verbose_name="المرحلة",
            ),
        ),
    ]
