# Generated by Django 4.2.23 on 2025-12-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0013_department_reporttype_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="إن تُركت فارغة يكون الإشعار عامًا أو على مستوى كل المدارس.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="reports.school",
                verbose_name="المدرسة المستهدفة",
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("role_type", "manager")),
                fields=("school",),
                name="uniq_active_manager_per_school",
            ),
        ),
    ]
