# Generated by Django 4.2.23 on 2025-12-16 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0014_notification_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="schools/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "svg", "webp"]
                    )
                ],
                verbose_name="شعار مرفوع",
            ),
        ),
    ]
