# Generated by Django 4.2.23 on 2025-12-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_school_logo_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="print_primary_color",
            field=models.CharField(
                blank=True,
                help_text="لون رئيسي لقالب الطباعة (مثلاً #2563eb).",
                max_length=9,
                null=True,
                verbose_name="لون قالب الطباعة",
            ),
        ),
    ]
