# Generated by Django 5.1.2 on 2025-12-17 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0016_school_print_primary_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الباقة")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
                (
                    "days_duration",
                    models.PositiveIntegerField(
                        help_text="مدة الباقة الافتراضية بالأيام (مثلاً 90 للفصل، 365 للسنة)",
                        verbose_name="المدة بالأيام",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="المميزات")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "باقة اشتراك",
                "verbose_name_plural": "باقات الاشتراكات",
            },
        ),
        migrations.AlterField(
            model_name="school",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="schools/logos/",
                verbose_name="شعار مرفوع",
            ),
        ),
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="تاريخ الانتهاء"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="يمكن استخدامه لتعطيل الاشتراك مؤقتاً بغض النظر عن التاريخ",
                        verbose_name="نشط يدوياً",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.subscriptionplan",
                        verbose_name="الباقة الحالية",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك مدرسة",
                "verbose_name_plural": "اشتراكات المدارس",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        help_text="يرجى إرفاق صورة التحويل البنكي",
                        upload_to="payments/receipts/%Y/%m/",
                        verbose_name="صورة الإيصال",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التحويل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "مقبول"),
                            ("rejected", "مرفوض"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات الإدارة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="قام بالرفع",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="reports.schoolsubscription",
                        verbose_name="الاشتراك المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية دفع",
                "verbose_name_plural": "المدفوعات والإيرادات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["end_date", "is_active"], name="reports_sch_end_dat_5ed243_idx"
            ),
        ),
    ]
