# Generated by Django 4.2.23 on 2025-12-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0017_subscriptionplan_alter_school_logo_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_platform",
            field=models.BooleanField(
                default=False,
                help_text="إذا تم تحديده، يعتبر هذا الطلب موجهاً لإدارة المنصة وليس للمدرسة داخلياً.",
                verbose_name="دعم فني للمنصة؟",
            ),
        ),
    ]
