# Generated by Django 4.2.27 on 2025-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0018_ticket_is_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(max_length=64, verbose_name="المعرّف (slug)"),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="code",
            field=models.SlugField(max_length=40, verbose_name="الكود"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["school", "slug"], name="reports_dep_school__e281a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttype",
            index=models.Index(
                fields=["school", "code"], name="reports_rep_school__530554_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", False)),
                fields=("school", "slug"),
                name="uniq_department_slug_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", True)),
                fields=("slug",),
                name="uniq_global_department_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", False)),
                fields=("school", "code"),
                name="uniq_reporttype_code_per_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", True)),
                fields=("code",),
                name="uniq_global_reporttype_code",
            ),
        ),
    ]
