# Generated by Django 4.2.27 on 2025-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0019_alter_department_slug_alter_reporttype_code_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["school", "report_date"], name="reports_rep_school__d69d5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["school", "created_at"], name="reports_rep_school__769675_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["school", "category"], name="reports_rep_school__17637d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["school", "status", "created_at"],
                name="reports_tic_school__f33ebc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["school", "assignee", "status"],
                name="reports_tic_school__83d0a3_idx",
            ),
        ),
    ]
