# Generated by Django 4.2.27 on 2025-12-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0020_report_reports_rep_school__d69d5c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_teachers",
            field=models.PositiveIntegerField(
                default=0,
                help_text="الحد الأقصى لعدد حسابات المعلمين داخل المدرسة. 0 = غير محدود.",
                verbose_name="حد المعلمين",
            ),
        ),
    ]
