# Generated by Django 4.2.27 on 2025-12-23 11:45

from django.db import migrations, models
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0021_subscriptionplan_max_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="reports/pdfs/", verbose_name="ملف PDF"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="pdf_status",
            field=models.CharField(
                choices=[
                    ("none", "لم يتم التوليد"),
                    ("pending", "في الانتظار"),
                    ("processing", "جاري التوليد"),
                    ("completed", "مكتمل"),
                    ("failed", "فشل"),
                ],
                default="none",
                max_length=20,
                verbose_name="حالة الـ PDF",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(
                help_text="يرجى إرفاق صورة التحويل البنكي",
                upload_to="payments/receipts/%Y/%m/",
                validators=[reports.validators.validate_image_file],
                verbose_name="صورة الإيصال",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reports/",
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reports/",
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reports/",
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reports/",
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="schools/logos/",
                validators=[reports.validators.validate_image_file],
                verbose_name="شعار مرفوع",
            ),
        ),
        migrations.AlterField(
            model_name="ticketimage",
            name="image",
            field=models.ImageField(
                upload_to="tickets/images/%Y/%m/%d/",
                validators=[reports.validators.validate_image_file],
                verbose_name="الصورة",
            ),
        ),
    ]
