# Generated by Django 5.1.2 on 2025-12-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0022_report_pdf_file_report_pdf_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إنشاء"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("login", "تسجيل دخول"),
                            ("logout", "تسجيل خروج"),
                        ],
                        max_length=20,
                        verbose_name="العملية",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم النموذج"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف السجل"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="وصف السجل"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="التغييرات"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="متصفح المستخدم"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل عمليات",
                "verbose_name_plural": "سجلات العمليات",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["school", "timestamp"],
                        name="reports_aud_school__edfd31_idx",
                    ),
                    models.Index(
                        fields=["teacher", "timestamp"],
                        name="reports_aud_teacher_ec7ccb_idx",
                    ),
                ],
            },
        ),
    ]
