# Generated by Django 5.1.2 on 2025-12-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0023_auditlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="report",
            name="pdf_status",
        ),
    ]
