# Generated by GitHub Copilot
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


def backfill_ticket_recipients(apps, schema_editor):
    Ticket = apps.get_model("reports", "Ticket")
    TicketRecipient = apps.get_model("reports", "TicketRecipient")

    # تعبئة المستلمين للتذاكر القديمة من assignee (توافق خلفي)
    qs = Ticket.objects.exclude(assignee_id__isnull=True).values_list("id", "assignee_id")
    to_create = []
    seen = set()
    for ticket_id, teacher_id in qs.iterator():
        key = (ticket_id, teacher_id)
        if key in seen:
            continue
        seen.add(key)
        to_create.append(TicketRecipient(ticket_id=ticket_id, teacher_id=teacher_id))

    if to_create:
        TicketRecipient.objects.bulk_create(to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0024_remove_report_pdf_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="ticket_recipient_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="ticket_recipients",
                        to="reports.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستلم تذكرة",
                "verbose_name_plural": "مستلمو التذاكر",
            },
        ),
        migrations.AddConstraint(
            model_name="ticketrecipient",
            constraint=models.UniqueConstraint(fields=("ticket", "teacher"), name="uniq_ticket_recipient"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets_received",
                through="reports.TicketRecipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستلمون",
            ),
        ),
        migrations.RunPython(backfill_ticket_recipients, migrations.RunPython.noop),
    ]
