# Generated by Django 4.2.27 on 2025-12-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0025_ticket_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmembership",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("teacher", "معلم"),
                    ("manager", "مدير مدرسة"),
                    ("report_viewer", "مشرف تقارير (عرض فقط)"),
                ],
                default="teacher",
                max_length=16,
                verbose_name="الدور داخل المدرسة",
            ),
        ),
    ]
