# Generated by Django 4.2.27 on 2025-12-31 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import reports.storage
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0026_alter_schoolmembership_role_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAchievementFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        db_index=True,
                        help_text="مثال: 1447-1448",
                        max_length=9,
                        verbose_name="السنة الدراسية (هجري)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "بانتظار الاعتماد"),
                            ("returned", "مُعاد للمعلّم"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المعلّم",
                    ),
                ),
                (
                    "teacher_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="رقم الجوال"
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="اسم المدرسة",
                    ),
                ),
                (
                    "school_stage",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="المرحلة"
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(blank=True, default="", verbose_name="المؤهلات"),
                ),
                (
                    "professional_experience",
                    models.TextField(
                        blank=True, default="", verbose_name="الخبرات المهنية"
                    ),
                ),
                (
                    "specialization",
                    models.TextField(blank=True, default="", verbose_name="التخصص"),
                ),
                (
                    "teaching_load",
                    models.TextField(blank=True, default="", verbose_name="نصاب الحصص"),
                ),
                (
                    "subjects_taught",
                    models.TextField(
                        blank=True, default="", verbose_name="مواد التدريس"
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True, default="", verbose_name="بيانات التواصل"
                    ),
                ),
                (
                    "manager_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="ملاحظات مدير المدرسة"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=reports.storage.PublicRawMediaStorage(),
                        upload_to=reports.models._achievement_pdf_upload_to,
                        verbose_name="ملف PDF",
                    ),
                ),
                (
                    "pdf_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر توليد PDF"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="achievement_files_decided",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتماد بواسطة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_files",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievement_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعلّم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف إنجاز",
                "verbose_name_plural": "ملفات الإنجاز",
            },
        ),
        migrations.CreateModel(
            name="AchievementSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1- أداء الواجبات الوظيفية"),
                            (2, "2- التفاعل مع المجتمع المهني"),
                            (3, "3- التفاعل مع أولياء الأمور"),
                            (4, "4- التنوع في استراتيجيات التدريس"),
                            (5, "5- تحسين نتائج المتعلمين"),
                            (6, "6- إعداد وتنفيذ خطة التعلم"),
                            (7, "7- توظيف تقنيات ووسائل التعلم المناسبة"),
                            (8, "8- تهيئة بيئة تعليمية"),
                            (9, "9- الإدارة الصفية"),
                            (10, "10- تحليل نتائج المتعلمين وتشخيص مستوياتهم"),
                            (11, "11- تنوع أساليب التقويم"),
                        ],
                        verbose_name="المحور",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="العنوان"
                    ),
                ),
                (
                    "teacher_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="ملاحظات المعلّم"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="reports.teacherachievementfile",
                        verbose_name="ملف الإنجاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "محور ملف إنجاز",
                "verbose_name_plural": "محاور ملفات الإنجاز",
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="AchievementEvidenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=reports.models._achievement_evidence_upload_to,
                        validators=[reports.validators.validate_image_file],
                        verbose_name="صورة الشاهد",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_images",
                        to="reports.achievementsection",
                        verbose_name="المحور",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة شاهد",
                "verbose_name_plural": "صور الشواهد",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="teacherachievementfile",
            index=models.Index(
                fields=["school", "academic_year", "status"],
                name="reports_tea_school__67f582_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherachievementfile",
            index=models.Index(
                fields=["teacher", "academic_year"],
                name="reports_tea_teacher_654a88_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherachievementfile",
            constraint=models.UniqueConstraint(
                fields=("teacher", "school", "academic_year"),
                name="uniq_teacher_achievement_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="achievementsection",
            constraint=models.UniqueConstraint(
                fields=("file", "code"), name="uniq_achievement_section_per_file"
            ),
        ),
    ]
