# Generated by Django 4.2.27 on 2025-12-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0027_teacherachievementfile_achievementsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="requested_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_requests",
                to="reports.subscriptionplan",
                verbose_name="الباقة المطلوبة",
            ),
        ),
    ]
