# Generated by Django 4.2.27 on 2026-01-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_sharelink_if_not_exists(apps, schema_editor):
    """إنشاء جدول ShareLink فقط إذا لم يكن موجوداً"""
    table_name = 'reports_sharelink'
    if table_name not in schema_editor.connection.introspection.table_names():
        # الجدول غير موجود، لا نفعل شيئاً هنا (سيتم إنشاءه عبر state_operations)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0028_payment_requested_plan"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # هذا يحدّث حالة Django فقط
                migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Token"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("report", "تقرير"), ("achievement", "ملف إنجاز")],
                        db_index=True,
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="مفعّل"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="ينتهي في"),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر وصول"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "achievement_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="reports.teacherachievementfile",
                        verbose_name="ملف الإنجاز",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="reports.report",
                        verbose_name="التقرير",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_links",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "رابط مشاركة",
                "verbose_name_plural": "روابط مشاركة",
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active", "expires_at"],
                        name="reports_sha_kind_48ab4c_idx",
                    ),
                    models.Index(
                        fields=["report", "is_active", "expires_at"],
                        name="reports_sha_report__807855_idx",
                    ),
                    models.Index(
                        fields=["achievement_file", "is_active", "expires_at"],
                        name="reports_sha_achieve_d55533_idx",
                    ),
                ],
            },
        ),
                migrations.AddConstraint(
                    model_name="sharelink",
                    constraint=models.CheckConstraint(
                        check=models.Q(
                            models.Q(
                                ("achievement_file__isnull", True),
                                ("kind", "report"),
                                ("report__isnull", False),
                            ),
                            models.Q(
                                ("achievement_file__isnull", False),
                                ("kind", "achievement"),
                                ("report__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="sharelink_kind_target_consistent",
                    ),
                ),
            ],
            # لا نقوم بأي عمليات قاعدة بيانات - فقط نحدث الحالة
            database_operations=[],
        ),
    ]
