# Generated by Django 4.2.27 on 2026-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0028_payment_requested_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="current_session_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
