# Generated by Django 4.2.27 on 2026-01-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0029_sharelink_sharelink_sharelink_kind_target_consistent"),
        ("reports", "0029_teacher_current_session_key"),
    ]

    operations = []
