# Generated by Django 4.2.27 on 2026-01-06 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0030_sharelink_sharelink_sharelink_kind_target_consistent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_link_default_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="المدة الافتراضية لروابط مشاركة التقارير/ملفات الإنجاز.",
                        verbose_name="مدة صلاحية رابط المشاركة (بالأيام)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخر تعديل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المنصة",
                "verbose_name_plural": "إعدادات المنصة",
            },
        ),
    ]
