# Generated by Django 4.2.27 on 2026-01-09 13:05

import django.core.validators
from django.db import migrations, models
import reports.models
import reports.storage
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0030_merge_20260109_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(
                help_text="يرجى إرفاق صورة التحويل البنكي",
                upload_to=reports.models._payment_receipt_upload_to,
                validators=[reports.validators.validate_image_file],
                verbose_name="صورة الإيصال",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reports.models._report_image_upload_to,
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reports.models._report_image_upload_to,
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reports.models._report_image_upload_to,
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="image4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reports.models._report_image_upload_to,
                validators=[reports.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="requestticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=reports.models._ticket_attachment_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    ),
                    reports.validators.validate_attachment_file,
                ],
                verbose_name="مرفق (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reports.models._school_logo_upload_to,
                validators=[reports.validators.validate_image_file],
                verbose_name="شعار مرفوع",
            ),
        ),
        migrations.AlterField(
            model_name="teacherachievementfile",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=reports.storage.PublicRawMediaStorage(),
                upload_to=reports.models._achievement_pdf_upload_to,
                validators=[reports.validators.validate_pdf_file],
                verbose_name="ملف PDF",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="يسمح بـ PDF/صور/DOCX حتى 5MB",
                null=True,
                storage=reports.storage.PublicRawMediaStorage(),
                upload_to=reports.models._ticket_attachment_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    ),
                    reports.validators.validate_attachment_file,
                ],
                verbose_name="مرفق",
            ),
        ),
        migrations.AlterField(
            model_name="ticketimage",
            name="image",
            field=models.ImageField(
                upload_to=reports.models._ticket_image_upload_to,
                validators=[reports.validators.validate_image_file],
                verbose_name="الصورة",
            ),
        ),
    ]
