# Generated by Django 4.2.27 on 2026-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0031_platformsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="share_link_default_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="المدة الافتراضية لروابط مشاركة التقارير/ملفات الإنجاز لهذه المدرسة.",
                verbose_name="مدة صلاحية الروابط الافتراضية (بالأيام)",
            ),
        ),
    ]
