# Generated by Django 4.2.27 on 2026-01-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0031_alter_payment_receipt_image_alter_report_image1_and_more"),
        ("reports", "0032_school_share_link_default_days"),
    ]

    operations = []
