# Generated by Django 4.2.27 on 2026-01-16 00:14

from django.db import migrations, models
import reports.models
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0035_notification_signatures"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationrecipient",
            new_name="reports_not_teacher_41325c_idx",
            old_name="reports_noti_teacher_issigned_created_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="يسمح بـ PDF/Word/صور. حد أقصى 5MB.",
                null=True,
                upload_to=reports.models._notification_attachment_upload_to,
                validators=[reports.validators.validate_attachment_file],
                verbose_name="مرفق (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("approved", "مقبول"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
