# Generated by Django 4.2.27 on 2026-01-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0036_rename_reports_noti_teacher_issigned_created_idx_reports_not_teacher_41325c_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="attachment",
        ),
    ]
