# Generated by Django 4.2.27 on 2026-01-17 06:17

from django.db import migrations, models
import reports.models
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0037_remove_notification_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="يسمح بـ PDF/صور. حد أقصى 5MB.",
                null=True,
                upload_to=reports.models._notification_attachment_upload_to,
                validators=[reports.validators.validate_circular_attachment_file],
                verbose_name="مرفق (اختياري)",
            ),
        ),
    ]
