# Generated by Django 4.2.27 on 2026-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0038_notification_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="allowed_academic_years",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="قائمة بالسنوات الدراسية (هجري) التي تظهر للمعلم عند إنشاء ملف إنجاز.",
                verbose_name="السنوات الدراسية المتاحة/المقبولة",
            ),
        ),
    ]
