# Generated by GitHub Copilot on 2026-01-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0039_school_allowed_academic_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
    ]
