# Generated by GitHub Copilot on 2026-01-17

from django.db import migrations


def force_teacher_fk_cascade_postgres(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
DO $$
DECLARE
    cname text;
    teacher_attnum int;
BEGIN
    -- Find attnum for reports_auditlog.teacher_id
    SELECT attnum INTO teacher_attnum
    FROM pg_attribute
    WHERE attrelid = 'reports_auditlog'::regclass
      AND attname = 'teacher_id'
      AND NOT attisdropped;

    -- Drop any existing FK from reports_auditlog.teacher_id -> reports_teacher.id
    SELECT c.conname INTO cname
    FROM pg_constraint c
    WHERE c.contype = 'f'
      AND c.conrelid = 'reports_auditlog'::regclass
      AND c.confrelid = 'reports_teacher'::regclass
      AND teacher_attnum IS NOT NULL
      AND teacher_attnum = ANY (c.conkey)
    LIMIT 1;

    IF cname IS NOT NULL THEN
        EXECUTE 'ALTER TABLE reports_auditlog DROP CONSTRAINT ' || quote_ident(cname);
    END IF;

    -- Recreate FK with ON DELETE CASCADE using a stable name
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid = 'reports_auditlog'::regclass
          AND conname = 'reports_auditlog_teacher_id_fk'
    ) THEN
        EXECUTE 'ALTER TABLE reports_auditlog '
            || 'ADD CONSTRAINT reports_auditlog_teacher_id_fk '
            || 'FOREIGN KEY (teacher_id) REFERENCES reports_teacher(id) '
            || 'ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
    END IF;
END $$;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0040_auditlog_teacher_cascade"),
    ]

    operations = [
        migrations.RunPython(force_teacher_fk_cascade_postgres, migrations.RunPython.noop),
    ]
