# Generated by Django 4.2.27 on 2026-01-19

from django.db import migrations, models
import reports.models
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0041_force_auditlog_teacher_fk_cascade_pg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                null=True,
                help_text="يرجى إرفاق صورة التحويل البنكي",
                upload_to=reports.models._payment_receipt_upload_to,
                validators=[reports.validators.validate_image_file],
                verbose_name="صورة الإيصال",
            ),
        ),
    ]
