# Generated by GitHub Copilot on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0042_alter_payment_receipt_image_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformadminscope",
            name="role",
            field=models.CharField(
                choices=[
                    ("general", "مشرف عام"),
                    ("education_manager", "مدير التعليم"),
                    ("minister", "وزير التعليم"),
                    ("resident", "مشرف مقيم"),
                ],
                default="general",
                max_length=32,
                verbose_name="الدور",
            ),
        ),
    ]
