# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0044_platform_admin_roles_dynamic"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmembership",
            name="job_title",
            field=models.CharField(
                choices=[
                    ("teacher", "معلم"),
                    ("admin_staff", "موظف إداري"),
                    ("lab_tech", "محضر مختبر"),
                ],
                default="teacher",
                help_text="للعرض فقط داخل المدرسة (بنفس الصلاحيات).",
                max_length=16,
                verbose_name="المسمى الوظيفي داخل المدرسة",
            ),
        ),
    ]
