# Generated by Django 4.2.27 on 2026-02-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0046_achievementevidencereport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="logo_file",
        ),
        migrations.RemoveField(
            model_name="school",
            name="logo_url",
        ),
    ]
