# Generated by Django 4.2.27 on 2026-02-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0047_remove_school_logo_file_remove_school_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformadminscope",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="يمكن إدارة الأدوار (إضافة/تعديل/حذف) من Django Admin.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scopes",
                to="reports.platformadminrole",
                verbose_name="الدور",
            ),
        ),
    ]
