# Generated by Django 4.2.27 on 2026-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0049_teacher_email"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["notification", "teacher"],
                name="reports_not_notific_8f4d50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["creator", "status"], name="reports_tic_creator_ab2a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["school", "creator", "status"],
                name="reports_tic_school__6e45ff_idx",
            ),
        ),
    ]
