# Generated by Django 4.2.27 on 2026-04-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0050_scalability_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["teacher", "school", "-report_date", "-id"],
                name="reports_rep_teacher_551018_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["school", "-report_date", "-id"],
                name="reports_rep_school__13d2c4_idx",
            ),
        ),
    ]
