# Generated by Django 4.2.27 on 2026-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0051_scale_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_broadcast",
            field=models.BooleanField(
                default=False,
                help_text="عند التفعيل يُعرض الإشعار/التعميم لجميع مستلميه دون تخصيص.",
                verbose_name="للجميع (بث عام)؟",
            ),
        ),
    ]
