# Generated by Django 4.2.27 on 2026-05-14 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0052_add_notification_is_broadcast"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolArchiveAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="مفعّل؟"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="تاريخ بداية الملحق",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="اتركه فارغًا إذا كان الملحق مفتوح المدة.",
                        null=True,
                        verbose_name="تاريخ نهاية الملحق",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="قيمة الملحق",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "ملحق أرشفة مدرسة",
                "verbose_name_plural": "ملحقات أرشفة المدارس",
            },
        ),
        migrations.AddField(
            model_name="report",
            name="academic_year",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="تُملأ تلقائيًا من إعدادات المدرسة عند إنشاء التقرير.",
                max_length=9,
                verbose_name="السنة الدراسية (هجري)",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="current_academic_year",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="مثال: 1447-1448. تُستخدم لتصنيف التقارير الجديدة وأرشفة السنوات.",
                max_length=9,
                verbose_name="السنة الدراسية الحالية (هجري)",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["school", "academic_year", "-report_date", "-id"],
                name="reports_rep_school__4e608b_idx",
            ),
        ),
        migrations.AddField(
            model_name="schoolarchiveaddon",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_addon",
                to="reports.school",
                verbose_name="المدرسة",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolarchiveaddon",
            index=models.Index(
                fields=["is_enabled", "end_date"], name="reports_sch_is_enab_ca5327_idx"
            ),
        ),
    ]
