# Generated by Django 4.2.27 on 2026-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0053_schoolarchiveaddon_report_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="archive_storage_gb",
            field=models.PositiveIntegerField(
                default=0,
                help_text="تستخدم فقط عند طلب زيادة مساحة تخزين الأرشيف.",
                verbose_name="مساحة أرشيف إضافية (GB)",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("subscription", "اشتراك المدرسة"),
                    ("archive_addon", "إضافة الأرشفة"),
                    ("archive_storage", "زيادة مساحة الأرشيف"),
                ],
                db_index=True,
                default="subscription",
                max_length=32,
                verbose_name="نوع العملية",
            ),
        ),
        migrations.AddField(
            model_name="schoolarchiveaddon",
            name="storage_limit_gb",
            field=models.PositiveIntegerField(
                default=50, verbose_name="حد التخزين (GB)"
            ),
        ),
        migrations.AddField(
            model_name="schoolarchiveaddon",
            name="storage_used_bytes",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="المستخدم من التخزين (بايت)"
            ),
        ),
    ]
