# Generated by Django 4.2.27 on 2026-05-14 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0054_payment_archive_storage_gb_payment_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="archive_addon_annual_price",
            field=models.DecimalField(
                decimal_places=2,
                default=399,
                help_text="السعر الذي يظهر لمدير المدرسة عند طلب تفعيل أو تجديد الأرشفة.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سعر إضافة الأرشفة السنوي",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="archive_included_storage_gb",
            field=models.PositiveIntegerField(
                default=50,
                help_text="المساحة التي يحصل عليها العميل عند تفعيل إضافة الأرشفة.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="مساحة الأرشفة المضمنة (GB)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="archive_storage_block_gb",
            field=models.PositiveIntegerField(
                default=50,
                help_text="حجم كل وحدة زيادة مساحة، مثال: 50GB.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="حجم باقة زيادة التخزين (GB)",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="archive_storage_block_price",
            field=models.DecimalField(
                decimal_places=2,
                default=99,
                help_text="سعر كل وحدة زيادة مساحة تخزين للأرشيف.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سعر باقة زيادة التخزين",
            ),
        ),
    ]
