# Generated by Django 4.2.27 on 2026-06-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0056_archivestorageoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
