# Generated by Django 4.2.27 on 2026-06-25 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0057_remove_teacher_role_delete_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم مختصر يظهر للمعلم في قائمة القوالب، مثل: الإذاعة الصباحية.",
                        max_length=120,
                        verbose_name="اسم القالب",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="يُعبّأ في حقل العنوان عند تطبيق القالب.",
                        max_length=255,
                        verbose_name="عنوان التقرير المقترح",
                    ),
                ),
                (
                    "idea",
                    models.TextField(
                        blank=True,
                        help_text="يُعبّأ في حقل تفاصيل التقرير عند تطبيق القالب.",
                        verbose_name="نص التفاصيل المقترح",
                    ),
                ),
                (
                    "beneficiaries_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغًا إذا لا ينطبق.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد المستفيدين المقترح",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="يُختار تلقائيًا عند تطبيق القالب (اختياري).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="reports.reporttype",
                        verbose_name="نوع التقرير",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_templates_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="يظهر هذا القالب فقط داخل المدرسة المحددة.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب تقرير",
                "verbose_name_plural": "قوالب التقارير",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["school", "is_active", "order"],
                        name="reports_rep_school__21b99f_idx",
                    )
                ],
            },
        ),
    ]
