# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0058_reporttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="maintenance_mode_enabled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="عند التفعيل تظهر شاشة الصيانة للمستخدمين ولا يمكنهم استخدام الموقع حتى إيقافها.",
                verbose_name="تفعيل وضع الصيانة والتطوير",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="maintenance_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="رسالة اختيارية تظهر للمستخدمين في شاشة الصيانة.",
                verbose_name="رسالة الصيانة",
            ),
        ),
    ]
