# Generated by Django 4.2.27 on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0059_platformsettings_maintenance_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("credential_id", models.BinaryField(unique=True, verbose_name="معرّف المفتاح")),
                (
                    "credential_id_hash",
                    models.CharField(db_index=True, max_length=64, unique=True, verbose_name="بصمة معرّف المفتاح"),
                ),
                ("public_key_cose", models.BinaryField(verbose_name="المفتاح العام")),
                ("sign_count", models.PositiveBigIntegerField(default=0, verbose_name="عداد التوقيع")),
                ("device_name", models.CharField(blank=True, default="", max_length=120, verbose_name="اسم الجهاز")),
                ("transports", models.JSONField(blank=True, default=list, verbose_name="وسائل النقل")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="نشط")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="آخر استخدام")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإضافة")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مفتاح دخول بالبصمة",
                "verbose_name_plural": "مفاتيح الدخول بالبصمة",
                "indexes": [models.Index(fields=["teacher", "is_active"], name="reports_web_teacher_fdbd24_idx")],
            },
        ),
    ]
