# Generated by Django 4.2.27 on 2026-06-25 20:14

import datetime

from django.db import migrations, models


def seed_academic_years(apps, schema_editor):
    """يزرع نطاقًا مبدئيًا من السنوات الهجرية (3 سابقة + 5 قادمة)."""
    AcademicYear = apps.get_model("reports", "AcademicYear")
    School = apps.get_model("reports", "School")

    today = datetime.date.today()
    g = today.year + (today.month - 1) / 12.0
    try:
        anchor = int(round((g - 622) * 33.0 / 32.0))
    except Exception:
        anchor = 1448

    starts = set(range(anchor - 3, anchor + 6))

    # ضمّ أي سنوات مستخدمة فعلًا في المدارس حتى لا تختفي من الخيارات
    try:
        for s in School.objects.all().only("current_academic_year", "allowed_academic_years"):
            cur = (getattr(s, "current_academic_year", "") or "").strip()
            if cur[:4].isdigit():
                starts.add(int(cur[:4]))
            for y in (getattr(s, "allowed_academic_years", None) or []):
                ys = str(y).strip()
                if ys[:4].isdigit():
                    starts.add(int(ys[:4]))
    except Exception:
        pass

    for i, st in enumerate(sorted(starts)):
        AcademicYear.objects.get_or_create(value=f"{st}-{st + 1}", defaults={"is_active": True, "order": i})


def unseed_academic_years(apps, schema_editor):
    apps.get_model("reports", "AcademicYear").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0060_webauthncredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        db_index=True,
                        max_length=9,
                        unique=True,
                        verbose_name="السنة الدراسية (هجري)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="نشطة (تظهر للمدارس)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُضيفت في"),
                ),
            ],
            options={
                "verbose_name": "سنة دراسية",
                "verbose_name_plural": "السنوات الدراسية",
                "ordering": ("-value",),
            },
        ),
        migrations.RunPython(seed_academic_years, unseed_academic_years),
    ]
