# Generated by Django 4.2.27 on 2026-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0061_academicyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="batch_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="يربط عمليات الدفع التي أُنشئت معًا ضمن طلب موحّد واحد (إيصال واحد).",
                max_length=32,
                verbose_name="مرجع الطلب الموحّد",
            ),
        ),
    ]
