# Generated by Django 4.2.27 on 2026-06-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0062_payment_batch_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="free_storage_mb",
            field=models.PositiveIntegerField(
                default=1024,
                help_text="الحد الأقصى لإجمالي حجم الصور والملفات لكل مدرسة غير مشتركة في إضافة الأرشفة. القيمة بالميجابايت (1024MB = 1GB). ضع 0 لإلغاء الحد (تخزين غير محدود).",
                verbose_name="حد التخزين المجاني لكل مدرسة (ميجابايت)",
            ),
        ),
    ]
