# Generated by Django 4.2.27 on 2026-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0063_platformsettings_free_storage_mb"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementevidenceimage",
            name="storage_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="achievementevidencereport",
            name="storage_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="report",
            name="storage_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="school",
            name="storage_used_bytes",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="إجمالي تزايدي لحجم ملفات المدرسة (تقارير + ملفات إنجاز + شواهد). يُحدّث تلقائيًا.",
                verbose_name="إجمالي التخزين المستخدم (بايت)",
            ),
        ),
        migrations.AddField(
            model_name="teacherachievementfile",
            name="storage_bytes",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
