# Generated by Django 4.2.27 on 2026-08-01 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0073_schoolmembership_weekly_summary_email_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolLeadershipPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        db_index=True,
                        max_length=9,
                        verbose_name="السنة الدراسية (هجري)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "قيد الإعداد"), ("completed", "مكتمل")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المدير",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="اسم المدرسة",
                    ),
                ),
                (
                    "leadership_vision",
                    models.TextField(
                        blank=True, default="", verbose_name="الرؤية القيادية"
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="الملخص التنفيذي"
                    ),
                ),
                (
                    "notable_achievements",
                    models.TextField(
                        blank=True, default="", verbose_name="أبرز المنجزات"
                    ),
                ),
                (
                    "improvement_priorities",
                    models.TextField(
                        blank=True, default="", verbose_name="أولويات التحسين"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leadership_portfolios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدير المدرسة",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_portfolios",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف الأداء القيادي",
                "verbose_name_plural": "ملفات الأداء القيادي",
                "ordering": ["-academic_year", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipPortfolioSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "التخطيط والتشغيل المدرسي"),
                            (2, "تحسين نواتج التعلم"),
                            (3, "قيادة الكادر والتنمية المهنية"),
                            (4, "البيئة المدرسية والانضباط والسلامة"),
                            (5, "الحوكمة واللجان وإدارة الموارد"),
                            (6, "الشراكة الأسرية والمجتمعية"),
                            (7, "التحول الرقمي والابتكار"),
                            (8, "المبادرات والمنجزات النوعية"),
                        ],
                        verbose_name="المحور",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="وصف الممارسات والشواهد"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="مكتمل"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="reports.schoolleadershipportfolio",
                        verbose_name="ملف الأداء القيادي",
                    ),
                ),
            ],
            options={
                "verbose_name": "محور أداء قيادي",
                "verbose_name_plural": "محاور الأداء القيادي",
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipEvidenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=reports.models._leadership_evidence_upload_to,
                        validators=[reports.validators.validate_image_file],
                        verbose_name="صورة الشاهد",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=180,
                        verbose_name="وصف الشاهد",
                    ),
                ),
                (
                    "storage_bytes",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_images",
                        to="reports.leadershipportfoliosection",
                        verbose_name="المحور",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاهد أداء قيادي",
                "verbose_name_plural": "شواهد الأداء القيادي",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="schoolleadershipportfolio",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year"),
                name="uniq_school_leadership_portfolio_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadershipportfoliosection",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "code"),
                name="uniq_leadership_section_per_portfolio",
            ),
        ),
    ]
