# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0077_schoolyeararchive_leadership_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipEvidenceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_evidences",
                        to="reports.report",
                        verbose_name="التقرير",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_reports",
                        to="reports.leadershipportfoliosection",
                        verbose_name="المحور",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير شاهد أداء قيادي",
                "verbose_name_plural": "تقارير شواهد الأداء القيادي",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="leadershipevidencereport",
            constraint=models.UniqueConstraint(
                fields=("section", "report"),
                name="uniq_leadership_section_report_evidence",
            ),
        ),
    ]
