# Generated by Django 5.2.16 on 2026-08-04 18:01

from django.db import migrations, models


def carry_over_purchased_storage(apps, schema_editor):
    """Move each school's bought capacity off the archive add-on onto the school.

    Storage used to live on SchoolArchiveAddon.storage_limit_gb, so a school
    that paid for extra space lost it when the yearly-archive add-on lapsed.
    Copying the full limit across is deliberately generous: no school may come
    out of this migration with less room than it had.
    """
    SchoolArchiveAddon = apps.get_model("reports", "SchoolArchiveAddon")
    School = apps.get_model("reports", "School")

    for addon in SchoolArchiveAddon.objects.all().iterator():
        limit_gb = int(addon.storage_limit_gb or 0)
        if limit_gb > 0:
            School.objects.filter(pk=addon.school_id).update(extra_storage_gb=limit_gb)


def drop_carried_over_storage(apps, schema_editor):
    School = apps.get_model("reports", "School")
    School.objects.update(extra_storage_gb=0)


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0086_flexible_teacher_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="storage_mb_per_teacher",
            field=models.PositiveIntegerField(
                default=200,
                help_text="تُضرب في سعة المعلمين المشتراة لتحديد المساحة الأساسية للمدرسة. مثال: 200MB × سعة 50 معلماً = 10GB. ضع 0 لإلغاء المساحة الأساسية المشتقة.",
                verbose_name="المساحة الأساسية لكل معلم (ميجابايت)",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="extra_storage_gb",
            field=models.PositiveIntegerField(
                default=0,
                help_text="تُضاف فوق المساحة الأساسية المشتقة من سعة المعلمين. تبقى فعّالة ما دام اشتراك المدرسة فعّالاً، ولا علاقة لها بإضافة الأرشفة السنوية.",
                verbose_name="مساحة تخزين إضافية مشتراة (GB)",
            ),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="free_storage_mb",
            field=models.PositiveIntegerField(
                default=1024,
                help_text="يُطبّق فقط على مدرسة بلا اشتراك فعّال. المدارس المشتركة تحصل على مساحة مشتقة من سعة المعلمين. القيمة بالميجابايت (1024MB = 1GB). ضع 0 لإلغاء الحد (تخزين غير محدود).",
                verbose_name="حد التخزين الأدنى لمدرسة بلا اشتراك فعّال (ميجابايت)",
            ),
        ),
        migrations.RunPython(
            carry_over_purchased_storage,
            drop_carried_over_storage,
        ),
    ]
