# Generated by Django 5.2.16 on 2026-08-04 21:33

from django.db import migrations, models

PREVIOUS_DEFAULT_MB = 200
NEW_DEFAULT_MB = 400


def raise_untouched_allowance(apps, schema_editor):
    """Lift installs still sitting on the old default.

    200MB per teacher gave a 25-teacher school 4.9GB, which one school year of
    report photos alone can exhaust. Anything an operator has already tuned away
    from the old default is left alone.
    """
    PlatformSettings = apps.get_model("reports", "PlatformSettings")
    PlatformSettings.objects.filter(storage_mb_per_teacher=PREVIOUS_DEFAULT_MB).update(
        storage_mb_per_teacher=NEW_DEFAULT_MB
    )


def restore_previous_allowance(apps, schema_editor):
    PlatformSettings = apps.get_model("reports", "PlatformSettings")
    PlatformSettings.objects.filter(storage_mb_per_teacher=NEW_DEFAULT_MB).update(
        storage_mb_per_teacher=PREVIOUS_DEFAULT_MB
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0087_school_storage_independent_of_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsettings",
            name="storage_mb_per_teacher",
            field=models.PositiveIntegerField(
                default=400,
                help_text="تُضرب في سعة المعلمين المشتراة لتحديد المساحة الأساسية للمدرسة، فتكبر المساحة بنفس نسبة نمو الفريق. مثال: 400MB × سعة 50 معلماً = 19.5GB. ضع 0 لإلغاء المساحة الأساسية المشتقة.",
                verbose_name="المساحة الأساسية لكل معلم (ميجابايت)",
            ),
        ),
        migrations.RunPython(raise_untouched_allowance, restore_previous_allowance),
    ]
