# Generated by Django 5.2.16 on 2026-08-05 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0088_storage_per_teacher_400"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المجموعة")),
                (
                    "code",
                    models.SlugField(
                        help_text="كود قصير لتمييز المجموعة.",
                        max_length=64,
                        unique=True,
                        verbose_name="المعرّف (code)",
                    ),
                ),
                (
                    "education_department",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="الارتباط التنظيمي للمدير التنفيذي.",
                        max_length=200,
                        verbose_name="إدارة التعليم",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة؟")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئت في"),
                ),
                (
                    "headquarters_school",
                    models.ForeignKey(
                        blank=True,
                        help_text="المدرسة التي يتخذها المدير التنفيذي مقراً له.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headquartered_groups",
                        to="reports.school",
                        verbose_name="مدرسة المقر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة مدارس متكاملة",
                "verbose_name_plural": "مجموعات المدارس المتكاملة",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="school",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="اختياري — المدارس المستقلة تُترك بلا مجموعة.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="reports.schoolgroup",
                verbose_name="مجموعة المدارس المتكاملة",
            ),
        ),
        migrations.CreateModel(
            name="SchoolGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[("executive_director", "مدير تنفيذي")],
                        default="executive_director",
                        max_length=32,
                        verbose_name="الدور داخل المجموعة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط؟")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="reports.schoolgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضوية مجموعة مدارس",
                "verbose_name_plural": "عضويات مجموعات المدارس",
                "indexes": [
                    models.Index(
                        fields=["group"], name="reports_sch_group_i_16a9f8_idx"
                    ),
                    models.Index(
                        fields=["user"], name="reports_sch_user_id_02e699_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("role_type", "executive_director")
                        ),
                        fields=("group",),
                        name="uniq_active_executive_director_per_group",
                    )
                ],
                "unique_together": {("group", "user", "role_type")},
            },
        ),
    ]
