# Generated by Django 5.2.16 on 2026-08-05 05:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0090_remove_supervisor_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupNotificationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("managers", "مديرو المدارس فقط"),
                            ("all", "جميع المنسوبين"),
                        ],
                        default="managers",
                        max_length=16,
                        verbose_name="المستقبلون",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="العنوان"
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(default=False, verbose_name="يتطلب توقيعاً؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="أُرسل في"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_batches",
                        to="reports.schoolgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_notification_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسِل",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعميم مجموعة",
                "verbose_name_plural": "تعاميم المجموعات",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="يُملأ فقط لتعاميم المدير التنفيذي. حذف الدفعة لا يسحب التعميم من المدرسة — فقد وصلها فعلاً، وسحبه تزوير للسجل.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="reports.groupnotificationbatch",
                verbose_name="دفعة تعميم المجموعة",
            ),
        ),
        migrations.AddIndex(
            model_name="groupnotificationbatch",
            index=models.Index(
                fields=["group", "-created_at"], name="reports_gro_group_i_748665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupnotificationbatch",
            index=models.Index(
                fields=["sender", "-created_at"], name="reports_gro_sender__080ebd_idx"
            ),
        ),
    ]
