# Generated by Django 5.2.16 on 2026-08-05 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor_names(apps, schema_editor):
    """تعبئة لقطة اسم الفاعل للسجلات القائمة.

    بدونها تبدأ الميزة بتاريخ فارغ: كل سجل سابق يعتمد على العلاقة وحدها،
    فيضيع صاحبه عند أول حذف حساب. الدور يُترك فارغاً عمداً — لا يمكن معرفة ما
    كان دور المستخدم قبل شهور، واختلاق قيمة أسوأ من الفراغ الصادق.

    التنفيذ على دفعات عبر المحرّك مباشرة: القاعدة قد تحوي مئات الآلاف من
    الصفوف، وتحميلها في الذاكرة صف صف يخنق النشر.
    """
    AuditLog = apps.get_model("reports", "AuditLog")
    Teacher = apps.get_model("reports", "Teacher")

    actor_ids = (
        AuditLog.objects.filter(teacher__isnull=False, actor_name="")
        .values_list("teacher_id", flat=True)
        .distinct()
    )
    names = dict(
        Teacher.objects.filter(pk__in=list(actor_ids)).values_list("pk", "name")
    )
    for teacher_id, name in names.items():
        if not name:
            continue
        AuditLog.objects.filter(teacher_id=teacher_id, actor_name="").update(
            actor_name=str(name)[:150]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0091_group_notification_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="لقطة تبقى بعد حذف الحساب.",
                max_length=150,
                verbose_name="اسم الفاعل (وقت الحدث)",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الدور كما كان لحظة تنفيذ الإجراء، لا كما هو اليوم.",
                max_length=64,
                verbose_name="دور الفاعل (وقت الحدث)",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["teacher", "-timestamp"], name="reports_audit_actor_recent"
            ),
        ),
        migrations.RunPython(backfill_actor_names, migrations.RunPython.noop),
    ]
