# Generated by Django 5.2.16 on 2026-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0092_audit_log_integrity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmembership",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("teacher", "معلم"),
                    ("manager", "مدير مدرسة"),
                    ("deputy", "وكيل مدرسة"),
                    ("admin_staff", "موظف إداري"),
                ],
                default="teacher",
                max_length=16,
                verbose_name="الدور داخل المدرسة",
            ),
        ),
    ]
