# Generated by Django 5.2.16 on 2026-08-05 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0093_school_roles_deputy_admin_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("academic", "الشؤون التعليمية"),
                            ("operations", "الشؤون المدرسية"),
                            ("students", "شؤون الطلاب"),
                            ("shared", "صلاحيات مشتركة"),
                        ],
                        default="",
                        help_text="خاص بالوكيل. يوضّح مجال إشرافه ولا يمنح صلاحية بذاته.",
                        max_length=16,
                        verbose_name="مجال الوكالة",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="رموز من مرجع الصلاحيات في الكود. أي رمز مجهول يُسقَط عند الحفظ.",
                        verbose_name="الصلاحيات الممنوحة",
                    ),
                ),
                (
                    "template_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="القالب الذي انطلق منه المدير. يُفرَّغ عند أي تعديل يدوي بعده.",
                        max_length=64,
                        verbose_name="القالب المُطبَّق",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الأقسام التي يشرف عليها. تركها فارغة يعني نطاقاً بلا أقسام مُسندة.",
                        related_name="supervising_scopes",
                        to="reports.department",
                        verbose_name="الأقسام المشمولة",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_staff_scopes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مَن منح النطاق",
                    ),
                ),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope",
                        to="reports.schoolmembership",
                        verbose_name="العضوية",
                    ),
                ),
            ],
            options={
                "verbose_name": "نطاق صلاحية",
                "verbose_name_plural": "نطاقات الصلاحيات",
            },
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="الصلاحيات المفوَّضة"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="يظهر في سجل الإجراءات وفي شاشة المدير.",
                        max_length=255,
                        verbose_name="سبب التفويض",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="يبدأ في"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        help_text="التفويض بلا نهاية ليس تفويضاً — فالمدة إلزامية.",
                        verbose_name="ينتهي في",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="سُحب في"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المفوَّض إليه",
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المفوِّض",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegations_revoked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مَن سحبه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفويض",
                "verbose_name_plural": "التفويضات",
                "ordering": ("-starts_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "delegate", "-starts_at"],
                        name="reports_del_school__4d3570_idx",
                    ),
                    models.Index(
                        fields=["school", "-starts_at"],
                        name="reports_del_school__2550ab_idx",
                    ),
                ],
            },
        ),
    ]
