# Generated by Django 5.2.16 on 2026-08-05 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_reports_as_approved(apps, schema_editor):
    """كل تقرير قائم يُعتبر معتمداً.

    القرار الحاسم في هذا الترحيل. البديل — اعتبارها مسودات — يعيد فتح كل تقرير
    كُتب منذ إطلاق المنصة ويُغرق كل مدير بآلاف العناصر في صندوق اعتماده صباح
    النشر. وهو أيضاً كذبٌ على الواقع: تلك التقارير سُلّمت واعتُمدت خارج النظام
    فعلاً، وكان غياب الحقل هو ما أخفى ذلك لا غياب الاعتماد.

    ``decided_by`` يُترك فارغاً عمداً: لا يُعرف من اعتمدها، واختلاق معتمِد أسوأ
    من الفراغ الصادق. و``decided_at`` يأخذ تاريخ الإنشاء فيبقى الترتيب الزمني
    سليماً في أي شاشة تفرز بتاريخ القرار.
    """
    Report = apps.get_model("reports", "Report")
    Report.objects.update(approval_state="approved", decided_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reports", "0094_staff_scope_and_delegation"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="approval_state",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُرسل للمراجعة"),
                    ("under_review", "قيد المراجعة"),
                    ("needs_info", "بانتظار استكمال البيانات"),
                    ("recommended", "موصى باعتماده"),
                    ("returned", "مُعاد للملاحظة"),
                    ("approved", "معتمد"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
                verbose_name="حالة الاعتماد",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ القرار"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمده",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="review_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                verbose_name="آخر ملاحظة",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
        ),
        migrations.AddField(
            model_name="reporttype",
            name="approval_route",
            field=models.CharField(
                default="direct",
                help_text="من يراجع هذا النوع ومن يعتمده. الافتراضي: مباشرةً إلى مدير المدرسة.",
                max_length=16,
                verbose_name="مسار الاعتماد",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="معرّف السجل"
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المنفّذ (وقت الحدث)",
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="دور المنفّذ (وقت الحدث)",
                    ),
                ),
                (
                    "acted_as",
                    models.CharField(
                        choices=[("self", "بالأصالة"), ("delegate", "بالنيابة")],
                        default="self",
                        max_length=16,
                        verbose_name="صفة التنفيذ",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "إرسال للمراجعة"),
                            ("start_review", "بدء المراجعة"),
                            ("request_info", "طلب استكمال"),
                            ("return", "إعادة للملاحظة"),
                            ("recommend", "توصية بالاعتماد"),
                            ("approve", "اعتماد"),
                            ("withdraw", "سحب للتعديل"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="من حالة"
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="إلى حالة"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="الملاحظة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="وقت الإجراء"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_transitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المنفّذ",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="نوع السجل",
                    ),
                ),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_transitions_by_proxy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نيابةً عن",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_transitions",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "انتقال اعتماد",
                "verbose_name_plural": "انتقالات الاعتماد",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="reports_app_content_1e6454_idx",
                    ),
                    models.Index(
                        fields=["school", "-created_at"],
                        name="reports_app_school__60b602_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            mark_existing_reports_as_approved, migrations.RunPython.noop
        ),
    ]
