# Generated by Django 5.2.16 on 2026-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0095_report_approval_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="report_approval_enabled",
            field=models.BooleanField(
                default=False,
                help_text="عند تفعيلها يُنشأ التقرير مسودةً ويمر بالمراجعة والاعتماد قبل أن يصير نهائياً. وعند إيقافها يبقى التقرير نهائياً بمجرد حفظه.",
                verbose_name="تفعيل دورة اعتماد التقارير",
            ),
        ),
    ]
