# Generated by Django 5.2.16 on 2026-08-05 23:51

import django.core.validators
import django.db.models.deletion
import reports.model_parts.assignments
import reports.storage
import reports.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0096_school_report_approval_toggle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("school", "داخل المدرسة"),
                            ("group", "على مستوى المجموعة"),
                        ],
                        db_index=True,
                        default="school",
                        max_length=16,
                        verbose_name="نطاق التكليف",
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المكلِّف (وقت الإصدار)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان التكليف"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="المطلوب"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "تكليف مباشر"),
                            ("decision", "منبثق عن قرار"),
                            ("plan", "مهمة من خطة"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="مصدر التكليف",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "اعتيادي"), ("high", "عاجل")],
                        default="normal",
                        max_length=8,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="تكليفٌ بلا موعد لا يتأخر أبداً، فلا يُتابَع أبداً.",
                        verbose_name="موعد التسليم",
                    ),
                ),
                (
                    "requires_evidence",
                    models.BooleanField(
                        default=False,
                        help_text="عند التفعيل لا يُقبل إرسال التكليف للمراجعة بلا مرفقات.",
                        verbose_name="يتطلب شواهد؟",
                    ),
                ),
                (
                    "min_evidence_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="أقل عدد شواهد"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُلغي في"),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="سبب الإلغاء",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُصدر في"
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_cancelled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ألغاه",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="يُستعمل لتحديد من يراجع التنفيذ ضمن نطاقه.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="reports.department",
                        verbose_name="القسم المعني",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="لتكليف المدير التنفيذي على مدارس مجموعته.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="reports.schoolgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المكلِّف",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="للتكليف داخل مدرسة واحدة.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تكليف",
                "verbose_name_plural": "التكليفات",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AssignmentTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل للمراجعة"),
                            ("under_review", "قيد المراجعة"),
                            ("needs_info", "بانتظار استكمال البيانات"),
                            ("recommended", "موصى باعتماده"),
                            ("returned", "مُعاد للملاحظة"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                        verbose_name="آخر ملاحظة",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="قُبل في"),
                ),
                (
                    "clarification_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="يكتبه المكلَّف حين يحتاج بيان المطلوب قبل الشروع.",
                        verbose_name="طلب توضيح",
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="نسبة الإنجاز",
                    ),
                ),
                (
                    "progress_note",
                    models.TextField(
                        blank=True, default="", verbose_name="ملاحظات التنفيذ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُسند في"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المكلَّف",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="reports.assignment",
                        verbose_name="التكليف",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_targets",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مكلَّف",
                "verbose_name_plural": "المكلَّفون",
                "ordering": ("assignment_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="AssignmentEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF أو صورة أو مستند حتى 5MB.",
                        storage=reports.storage.PublicRawMediaStorage(),
                        upload_to=reports.model_parts.assignments._assignment_evidence_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "doc", "docx", "xlsx"]
                            ),
                            reports.validators.validate_attachment_file,
                        ],
                        verbose_name="الشاهد",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="وصف الشاهد",
                    ),
                ),
                (
                    "storage_bytes",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="رُفع في"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_evidence_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفعه",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="reports.assignmenttarget",
                        verbose_name="المكلَّف",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاهد تكليف",
                "verbose_name_plural": "شواهد التكليفات",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["school", "-created_at"], name="reports_ass_school__d744eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["group", "-created_at"], name="reports_ass_group_i_6f32d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["issuer", "-created_at"], name="reports_ass_issuer__f6b14d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["due_at"], name="reports_ass_due_at_5b6e4d_idx"),
        ),
        migrations.AddIndex(
            model_name="assignmenttarget",
            index=models.Index(
                fields=["assignee", "approval_state"],
                name="reports_ass_assigne_53d404_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignmenttarget",
            index=models.Index(
                fields=["school", "approval_state"],
                name="reports_ass_school__99d616_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmenttarget",
            constraint=models.UniqueConstraint(
                fields=("assignment", "assignee"),
                name="uniq_assignment_target_per_assignee",
            ),
        ),
    ]
