# Generated by Django 5.2.16 on 2026-08-06 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0097_assignments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("school", "اجتماع مدرسة"),
                            ("group", "مجلس مجموعة المدارس"),
                        ],
                        db_index=True,
                        default="school",
                        max_length=16,
                        verbose_name="نطاق الاجتماع",
                    ),
                ),
                (
                    "organizer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المنظّم (وقت الإنشاء)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الاجتماع"),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, default="", verbose_name="الغرض"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(db_index=True, verbose_name="موعد الانعقاد"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="المكان"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدول"),
                            ("held", "منعقد"),
                            ("cancelled", "ملغى"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "held_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انعقد في"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="سبب الإلغاء",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُنشئ في"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="يحدّد من يشرف عليه ضمن نطاقه.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="reports.department",
                        verbose_name="اللجنة / القسم",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="reports.schoolgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings_organized",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منظّم الاجتماع",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "اجتماع",
                "verbose_name_plural": "الاجتماعات",
                "ordering": ("-scheduled_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MeetingAgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="الترتيب"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="البند")),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="تمهيد / مرفقات"
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="reports.meeting",
                        verbose_name="الاجتماع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند جدول أعمال",
                "verbose_name_plural": "بنود جدول الأعمال",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="الترتيب"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("decision", "قرار"), ("recommendation", "توصية")],
                        default="decision",
                        max_length=16,
                        verbose_name="النوع",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="نص القرار")),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="التفصيل"),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="موعد التنفيذ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_decision",
                        to="reports.assignment",
                        verbose_name="التكليف المنبثق",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions_responsible",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسؤول عن التنفيذ",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="reports.meeting",
                        verbose_name="الاجتماع",
                    ),
                ),
                (
                    "agenda_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="reports.meetingagendaitem",
                        verbose_name="البند",
                    ),
                ),
            ],
            options={
                "verbose_name": "قرار",
                "verbose_name_plural": "القرارات",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="الاسم (وقت الدعوة)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "مدعو"),
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("excused", "معتذر"),
                        ],
                        default="invited",
                        max_length=16,
                        verbose_name="الحضور",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="ملاحظة"
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="reports.meeting",
                        verbose_name="الاجتماع",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المدعو",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور اجتماع",
                "verbose_name_plural": "حضور الاجتماعات",
                "ordering": ("person_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="MeetingMinutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل للمراجعة"),
                            ("under_review", "قيد المراجعة"),
                            ("needs_info", "بانتظار استكمال البيانات"),
                            ("recommended", "موصى باعتماده"),
                            ("returned", "مُعاد للملاحظة"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                        verbose_name="آخر ملاحظة",
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="نص المحضر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="reports.meeting",
                        verbose_name="الاجتماع",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minutes_written",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="كاتب المحضر",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
            ],
            options={
                "verbose_name": "محضر اجتماع",
                "verbose_name_plural": "محاضر الاجتماعات",
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["school", "-scheduled_at"],
                name="reports_mee_school__d97795_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["group", "-scheduled_at"], name="reports_mee_group_i_e84b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organizer", "-scheduled_at"],
                name="reports_mee_organiz_91690c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["meeting", "order"], name="reports_dec_meeting_dc4fbb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingattendee",
            constraint=models.UniqueConstraint(
                fields=("meeting", "person"), name="uniq_meeting_attendee"
            ),
        ),
    ]
