# Generated by Django 5.2.16 on 2026-08-06 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0098_meetings_and_decisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل للمراجعة"),
                            ("under_review", "قيد المراجعة"),
                            ("needs_info", "بانتظار استكمال البيانات"),
                            ("recommended", "موصى باعتماده"),
                            ("returned", "مُعاد للملاحظة"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                        verbose_name="آخر ملاحظة",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("school", "خطة مدرسة"),
                            ("group", "خطة تحسين مشتركة"),
                        ],
                        db_index=True,
                        default="school",
                        max_length=16,
                        verbose_name="نطاق الخطة",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المُعِدّ (وقت الإنشاء)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان الخطة")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="وصف الخطة"),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=9,
                        verbose_name="السنة الدراسية (هجري)",
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, null=True, verbose_name="تبدأ في"),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="تنتهي في"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("preparing", "قيد الإعداد"),
                            ("running", "قيد التنفيذ"),
                            ("closed", "مُغلقة"),
                        ],
                        db_index=True,
                        default="preparing",
                        max_length=16,
                        verbose_name="مرحلة التنفيذ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُنشئت في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="reports.schoolgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_owned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُعِدّ الخطة",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة",
                "verbose_name_plural": "الخطط",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل للمراجعة"),
                            ("under_review", "قيد المراجعة"),
                            ("needs_info", "بانتظار استكمال البيانات"),
                            ("recommended", "موصى باعتماده"),
                            ("returned", "مُعاد للملاحظة"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                        verbose_name="آخر ملاحظة",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المقدّم (وقت الاقتراح)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المبادرة"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="", verbose_name="الفكرة والأثر"
                    ),
                ),
                (
                    "is_best_practice",
                    models.BooleanField(
                        default=False,
                        help_text="تُقترح كممارسة تصلح لغير هذه المدرسة.",
                        verbose_name="ممارسة ناجحة؟",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شُوركت مع المجموعة في"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُنشئت في"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiatives",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiatives_shared",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="شاركها",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiatives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مقدّم المبادرة",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiatives",
                        to="reports.plan",
                        verbose_name="الخطة المرتبطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مبادرة",
                "verbose_name_plural": "المبادرات",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PlanGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="الترتيب"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="الهدف")),
                (
                    "indicator",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="مؤشر القياس",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="المستهدف"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="reports.plan",
                        verbose_name="الخطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "هدف خطة",
                "verbose_name_plural": "أهداف الخطط",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="الترتيب"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="المهمة")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="التفصيل"),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="موعد التنفيذ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_plan_task",
                        to="reports.assignment",
                        verbose_name="التكليف المنبثق",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_tasks",
                        to="reports.department",
                        verbose_name="القسم المعني",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="reports.plangoal",
                        verbose_name="الهدف",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="reports.plan",
                        verbose_name="الخطة",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة خطة",
                "verbose_name_plural": "مهام الخطط",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["school", "-created_at"], name="reports_pla_school__f7cc5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["group", "-created_at"], name="reports_pla_group_i_da42ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(
                fields=["school", "-created_at"], name="reports_ini_school__8f464c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(
                fields=["school", "approval_state"],
                name="reports_ini_school__9315b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plantask",
            index=models.Index(
                fields=["plan", "order"], name="reports_pla_plan_id_c2866a_idx"
            ),
        ),
    ]
