# Generated by Django 5.2.16 on 2026-08-06 03:16

import django.core.validators
import django.db.models.deletion
import reports.model_parts.documents
import reports.storage
import reports.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0099_plans_and_initiatives"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل للمراجعة"),
                            ("under_review", "قيد المراجعة"),
                            ("needs_info", "بانتظار استكمال البيانات"),
                            ("recommended", "موصى باعتماده"),
                            ("returned", "مُعاد للملاحظة"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                        verbose_name="آخر ملاحظة",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم الرافع (وقت الرفع)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="عنوان الوثيقة"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="وصف مختصر"),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=9,
                        verbose_name="السنة الدراسية (هجري)",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("minutes", "محضر"),
                            ("circular", "تعميم أو خطاب"),
                            ("letter", "مخاطبة رسمية"),
                            ("report", "تقرير"),
                            ("form", "نموذج أو استمارة"),
                            ("financial", "مستند مالي"),
                            ("contract", "عقد أو اتفاقية"),
                            ("certificate", "شهادة أو خطاب شكر"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=16,
                        verbose_name="نوع الوثيقة",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF أو صورة أو مستند حتى 5MB.",
                        storage=reports.storage.PublicRawMediaStorage(),
                        upload_to=reports.model_parts.documents._document_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            ),
                            reports.validators.validate_attachment_file,
                        ],
                        verbose_name="الملف",
                    ),
                ),
                (
                    "storage_bytes",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="رُفعت في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="reports.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_owned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صاحب الوثيقة",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رافع الوثيقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "وثيقة",
                "verbose_name_plural": "الوثائق",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "-created_at"],
                        name="reports_doc_school__f7e827_idx",
                    ),
                    models.Index(
                        fields=["school", "approval_state"],
                        name="reports_doc_school__543395_idx",
                    ),
                    models.Index(
                        fields=["school", "academic_year", "kind"],
                        name="reports_doc_school__8ce9ea_idx",
                    ),
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="reports_doc_owner_i_0634da_idx",
                    ),
                ],
            },
        ),
    ]
