# Generated by Django 5.2.16 on 2026-08-06 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_existing_leadership_status(apps, schema_editor):
    """ملفات الأداء القائمة تأخذ ما يقابل حالتها السابقة.

    ``completed`` كان يعني «فرغتُ منه» فيصير ``approved``: تلك الملفات اعتُمدت
    خارج النظام فعلاً، وإعادةُ فتحها تُلزم كل مدير بإعادة إرسال ما أنهاه.
    و``draft`` يبقى مسودة.

    ``decided_by`` يُترك فارغاً عمداً: لا يُعرف من اعتمدها، واختلاق معتمِد أسوأ
    من الفراغ الصادق — وهو القرار نفسه المتّبع في ترحيل التقارير.
    """
    Portfolio = apps.get_model("reports", "SchoolLeadershipPortfolio")
    Portfolio.objects.filter(status="completed").update(
        approval_state="approved", decided_at=models.F("updated_at")
    )
    Portfolio.objects.filter(status="draft").update(approval_state="draft")


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0100_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="approval_state",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُرسل للمراجعة"),
                    ("under_review", "قيد المراجعة"),
                    ("needs_info", "بانتظار استكمال البيانات"),
                    ("recommended", "موصى باعتماده"),
                    ("returned", "مُعاد للملاحظة"),
                    ("approved", "معتمد"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
                verbose_name="حالة الاعتماد",
            ),
        ),
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ القرار"
            ),
        ),
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمده",
            ),
        ),
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="review_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                verbose_name="آخر ملاحظة",
            ),
        ),
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
        ),
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AddField(
            model_name="schoolleadershipportfolio",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
        ),
        migrations.CreateModel(
            name="CircularDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل للمراجعة"),
                            ("under_review", "قيد المراجعة"),
                            ("needs_info", "بانتظار استكمال البيانات"),
                            ("recommended", "موصى باعتماده"),
                            ("returned", "مُعاد للملاحظة"),
                            ("approved", "معتمد"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="أُرسل في"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="رُوجع في"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ملاحظة آخر إجراء — تُعرض لصاحب العمل. والسجل الكامل في الانتقالات.",
                        verbose_name="آخر ملاحظة",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="اسم المُعِدّ (وقت الإعداد)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="عنوان التعميم"),
                ),
                ("body", models.TextField(verbose_name="نص التعميم")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "جميع المنسوبين"),
                            ("department", "قسم بعينه"),
                        ],
                        default="all",
                        max_length=16,
                        verbose_name="الفئة المستهدفة",
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=True,
                        help_text="عند التفعيل يُطلب من المستلم الإقرار وإدخال جواله قبل اعتماد توقيعه.",
                        verbose_name="يتطلب توقيعاً؟",
                    ),
                ),
                (
                    "signature_deadline_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر موعد للتوقيع"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="نُشر في"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُنشئت في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمده",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="circular_drafts",
                        to="reports.department",
                        verbose_name="القسم المستهدف",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circular_drafts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُعِدّ المسودة",
                    ),
                ),
                (
                    "published_notification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draft",
                        to="reports.notification",
                        verbose_name="التعميم المنشور",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="راجعه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circular_drafts",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسودة تعميم",
                "verbose_name_plural": "مسودات التعاميم",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "-created_at"],
                        name="reports_cir_school__d13efa_idx",
                    ),
                    models.Index(
                        fields=["school", "approval_state"],
                        name="reports_cir_school__2df7f1_idx",
                    ),
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="reports_cir_owner_i_d663ec_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            map_existing_leadership_status, migrations.RunPython.noop
        ),
    ]
