# Generated by Django 5.2.16 on 2026-08-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0101_circular_drafts_and_leadership_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolarchiveaddon",
            name="storage_limit_gb",
            field=models.PositiveIntegerField(
                default=50,
                help_text="مساحة الأرشفة وحدها، مستقلة عن مساحة عمل المدرسة اليومية.",
                verbose_name="حد مساحة النسخ السنوية (GB)",
            ),
        ),
        migrations.AlterField(
            model_name="schoolarchiveaddon",
            name="storage_used_bytes",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="مجموع أحجام النسخ السنوية المحفوظة فقط. يُحدَّث تلقائيًا ولا يشمل ملفات العمل اليومي.",
                verbose_name="المستخدم من مساحة النسخ السنوية (بايت)",
            ),
        ),
    ]
