# Generated by Django 5.2.16 on 2026-08-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0104_lab_assets_and_experiments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivestorageoption",
            options={
                "ordering": ["bucket", "sort_order", "storage_gb", "id"],
                "verbose_name": "خيار زيادة مساحة",
                "verbose_name_plural": "خيارات زيادة المساحة",
            },
        ),
        migrations.AddField(
            model_name="archivestorageoption",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("work", "مساحة عمل المدرسة"),
                    ("archive", "مساحة الأرشفة السنوية"),
                ],
                db_index=True,
                default="work",
                help_text="عمل المدرسة: التقارير والإنجاز والوثائق والمرفقات. الأرشفة السنوية: النسخ الثابتة المحفوظة لكل سنة.",
                max_length=16,
                verbose_name="المساحة المستهدفة",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="archive_storage_gb",
            field=models.PositiveIntegerField(
                default=0,
                help_text="تُستخدم في طلبات زيادة المساحة. يحدّد ``الغرض`` أي مساحة تُضاف إليها: عمل المدرسة أم الأرشفة السنوية.",
                verbose_name="المساحة الإضافية المطلوبة (GB)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("subscription", "اشتراك المدرسة"),
                    ("archive_addon", "إضافة الأرشفة"),
                    ("archive_storage", "زيادة مساحة عمل المدرسة"),
                    ("archive_space", "زيادة مساحة الأرشفة السنوية"),
                ],
                db_index=True,
                default="subscription",
                max_length=32,
                verbose_name="نوع العملية",
            ),
        ),
    ]
