# Generated by Django 5.2.16 on 2026-08-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0106_generated_export_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payer_group",
            field=models.ForeignKey(
                blank=True,
                help_text="تُملأ حين يدفع المدير التنفيذي نيابةً عن إحدى مدارس مجموعته.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_payments",
                to="reports.schoolgroup",
                verbose_name="المجموعة الدافعة",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer_kind",
            field=models.CharField(
                choices=[
                    ("school", "إدارة المدرسة"),
                    ("group_director", "المدير التنفيذي للمجموعة"),
                    ("platform", "إدارة المنصة"),
                ],
                db_index=True,
                default="school",
                max_length=20,
                verbose_name="صفة الدافع",
            ),
        ),
    ]
