# Generated by Django 5.2.16 on 2026-08-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0108_reconcile_paid_plan_entitlements"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="passkey_prompt_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="يوقف الدعوة التلقائية فقط؛ يبقى التفعيل متاحًا من إعدادات الأمان.",
                verbose_name="عدم عرض دعوة تفعيل البصمة مجددًا",
            ),
        ),
    ]
