# Generated by Django 5.2.16 on 2026-08-10 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0110_lab_experiment_flexible_drafts"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="WebPushDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الإرسال"),
                            ("sent", "تم الإرسال"),
                            ("failed", "تعذر الإرسال"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_push_deliveries",
                        to="reports.notification",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="reports.webpushsubscription",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="webpushsubscription",
            index=models.Index(
                fields=["teacher", "is_active"], name="reports_web_teacher_7ac2bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webpushsubscription",
            index=models.Index(
                fields=["is_active", "updated_at"],
                name="reports_web_is_acti_193d65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webpushdelivery",
            index=models.Index(
                fields=["status", "created_at"], name="reports_web_status_a42dce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webpushdelivery",
            constraint=models.UniqueConstraint(
                fields=("subscription", "notification"),
                name="uniq_web_push_delivery_subscription_notification",
            ),
        ),
    ]
