# Generated by Django 5.2.16 on 2026-08-12 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # يعتمد على 0114 لا على 0113: كلاهما أُنشئ من الفرع نفسه، وربطُهما
        # بالتسلسل يُبقي التاريخ خطياً بلا ترحيل دمجٍ لا يفعل شيئاً.
        ("reports", "0114_platform_voice_report_toggle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErasureRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="اختياري. يساعد على تحديد المسوّغ النظامي بدقة.",
                        verbose_name="سبب الطلب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "مستلَم"),
                            ("in_review", "قيد الدراسة"),
                            ("completed", "نُفِّذ"),
                            ("refused", "مرفوض بمسوّغ نظامي"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "response_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="يُبلَّغ به صاحب الطلب. الرفض يجب أن يذكر مسوّغه النظامي.",
                        verbose_name="ردّ المنصة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الطلب"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ البتّ"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erasure_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بتَّ فيه",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erasure_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صاحب الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب إتلاف بيانات",
                "verbose_name_plural": "طلبات إتلاف البيانات",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="reports_era_status_6459b6_idx",
                    ),
                    models.Index(
                        fields=["teacher", "-created_at"],
                        name="reports_era_teacher_1aa054_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["received", "in_review"])),
                        fields=("teacher",),
                        name="one_open_erasure_request_per_teacher",
                    )
                ],
            },
        ),
    ]
