# Generated by Django 5.2.16 on 2026-08-12 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0115_erasure_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="لأي نظام هذا المفتاح؟ يظهر في السجل عند كل استعمال.",
                        max_length=120,
                        verbose_name="اسم التكامل",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="المعرِّف العلني",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="تجزئة المفتاح",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("read", "قراءة فقط"), ("write", "قراءة وكتابة")],
                        default="read",
                        max_length=10,
                        verbose_name="النطاق",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="اتركه فارغاً لمفتاح دائم. المفاتيح المؤقّتة أأمن.",
                        null=True,
                        verbose_name="ينتهي في",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استعمال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "acting_as",
                    models.ForeignKey(
                        help_text="لا يملك المفتاح أكثر مما يملكه هذا الشخص في هذه المدرسة.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys_acting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="يعمل بصلاحيات",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_keys_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأه",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مفتاح تكامل",
                "verbose_name_plural": "مفاتيح التكامل",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "is_active"],
                        name="reports_sch_school__2c1cad_idx",
                    )
                ],
            },
        ),
    ]
