# Generated by Django 5.2.16 on 2026-08-12 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0116_school_api_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherTotpDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret_encrypted",
                    models.TextField(
                        editable=False,
                        help_text="لا يُخزَّن نصاً: تسريب نسخة من القاعدة كان سيُبطل العامل الثاني للجميع.",
                        verbose_name="السرّ (مُعمّى)",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="فارغ = تسجيلٌ بدأ ولم يكتمل. الجهاز غير النافذ لا يُطالَب به عند الدخول.",
                        null=True,
                        verbose_name="تاريخ التفعيل",
                    ),
                ),
                (
                    "last_used_counter",
                    models.BigIntegerField(
                        blank=True,
                        editable=False,
                        help_text="يمنع إعادة استعمال الرمز نفسه داخل نافذته.",
                        null=True,
                        verbose_name="آخر عدّاد مستعمَل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استعمال"
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز مصادقة ثنائية",
                "verbose_name_plural": "أجهزة المصادقة الثنائية",
            },
        ),
        migrations.CreateModel(
            name="TotpRecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=64,
                        verbose_name="تجزئة الرمز",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاستعمال"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to="reports.teachertotpdevice",
                        verbose_name="الجهاز",
                    ),
                ),
            ],
            options={
                "verbose_name": "رمز استرجاع",
                "verbose_name_plural": "رموز الاسترجاع",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "code_hash"),
                        name="unique_recovery_code_per_device",
                    )
                ],
            },
        ),
    ]
