# Generated by Django 5.2.16 on 2026-08-12 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0119_report_trash"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformEmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        default="منصة توثيق", max_length=120, verbose_name="اسم المرسل"
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        default="notifications@tawtheeq-ksa.com",
                        max_length=254,
                        verbose_name="بريد الإرسال",
                    ),
                ),
                (
                    "inbound_email",
                    models.EmailField(
                        default="support@mail.tawtheeq-ksa.com",
                        max_length=254,
                        verbose_name="بريد الاستقبال",
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        default="support@mail.tawtheeq-ksa.com",
                        max_length=254,
                        verbose_name="بريد الردود",
                    ),
                ),
                (
                    "is_sending_enabled",
                    models.BooleanField(default=False, verbose_name="الإرسال مفعّل"),
                ),
                (
                    "is_receiving_enabled",
                    models.BooleanField(default=False, verbose_name="الاستقبال مفعّل"),
                ),
                (
                    "retention_days",
                    models.PositiveSmallIntegerField(
                        default=365, verbose_name="مدة الاحتفاظ بالأيام"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعداد بريد المنصة",
                "verbose_name_plural": "إعدادات بريد المنصة",
            },
        ),
        migrations.CreateModel(
            name="PlatformEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "وارد"), ("outbound", "مرسل")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "مستلمة"),
                            ("queued", "في الانتظار"),
                            ("sent", "مرسلة"),
                            ("delivered", "تم التسليم"),
                            ("delayed", "متأخرة"),
                            ("bounced", "مرتدة"),
                            ("complained", "شكوى بريدية"),
                            ("failed", "فشل الإرسال"),
                            ("suppressed", "موقوفة"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("thread_key", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("from_email", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, default="", max_length=160)),
                ("to_emails", models.JSONField(default=list)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("bcc_emails", models.JSONField(blank=True, default=list)),
                ("reply_to_emails", models.JSONField(blank=True, default=list)),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="(بدون موضوع)", max_length=500
                    ),
                ),
                ("text_body", models.TextField(blank=True, default="")),
                ("html_body", models.TextField(blank=True, default="")),
                ("snippet", models.CharField(blank=True, default="", max_length=320)),
                ("raw_headers", models.JSONField(blank=True, default=dict)),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_starred", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("opened_count", models.PositiveIntegerField(default=0)),
                ("clicked_count", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_emails_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="reports.platformemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة بريد المنصة",
                "verbose_name_plural": "بريد المنصة",
                "ordering": ("-last_event_at", "-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PlatformEmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "content_disposition",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "content_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.platformemail",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PlatformEmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_event_id", models.CharField(max_length=160, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="reports.platformemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث بريد",
                "verbose_name_plural": "أحداث البريد",
                "ordering": ("-occurred_at", "-received_at"),
            },
        ),
        migrations.AddIndex(
            model_name="platformemail",
            index=models.Index(
                fields=["direction", "is_archived", "-created_at"],
                name="rpt_mail_folder_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformemail",
            index=models.Index(
                fields=["status", "-created_at"], name="rpt_mail_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformemailattachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_id", ""), _negated=True),
                fields=("email", "provider_id"),
                name="rpt_mail_attachment_provider_uq",
            ),
        ),
    ]
