# Generated by Django 5.2.16 on 2026-08-18 11:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0122_report_submission_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="ما خُصم من هذا البند بكود خصم. ``amount`` هو الصافي بعد الخصم.",
                max_digits=10,
                verbose_name="قيمة الخصم",
            ),
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="أحرف إنجليزية كبيرة وأرقام (والشرطة -). يُوحَّد تلقائياً إلى أحرف كبيرة.",
                        max_length=32,
                        unique=True,
                        verbose_name="الكود",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        default="percent",
                        max_length=16,
                        verbose_name="نوع الخصم",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="نسبة مئوية (حتى 100) أو مبلغ بالريال حسب نوع الخصم.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="قيمة الخصم",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        help_text="إجمالي مرات الاستخدام المتاحة لجميع المدارس. كل مدرسة تستخدم الكود مرة واحدة فقط.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الاستخدامات الكلي",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="اتركه فارغاً ليسري فوراً.",
                        null=True,
                        verbose_name="يسري من",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="آخر يوم يُقبل فيه الكود. اتركه فارغاً بلا تاريخ انتهاء.",
                        null=True,
                        verbose_name="يسري حتى",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="نشط"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="ملاحظات داخلية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_discount_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أصدره",
                    ),
                ),
            ],
            options={
                "verbose_name": "كود خصم",
                "verbose_name_plural": "أكواد الخصم",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="reports.discountcode",
                verbose_name="كود الخصم",
            ),
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="مرجع الطلب الموحّد",
                    ),
                ),
                (
                    "amount_discounted",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="قيمة الخصم الممنوحة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الاستخدام"
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="reports.discountcode",
                        verbose_name="كود الخصم",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_redemptions",
                        to="reports.payment",
                        verbose_name="عملية الدفع",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_redemptions",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "استخدام كود خصم",
                "verbose_name_plural": "استخدامات أكواد الخصم",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "school"), name="uniq_discount_code_per_school"
                    )
                ],
            },
        ),
    ]
