# Generated by Django 5.2.17 on 2026-08-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0126_school_identity_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrecipient",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="يُملأ فقط عند إلحاق مستلم بعد إصدار التعميم.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_recipient_additions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أضافه",
            ),
        ),
        migrations.AddField(
            model_name="notificationrecipient",
            name="delivery_source",
            field=models.CharField(
                choices=[
                    ("original", "ضمن قائمة الإصدار الأصلية"),
                    ("manual_addition", "أُضيف لاحقًا بواسطة الإدارة"),
                ],
                default="original",
                help_text="يميّز قائمة الإصدار الأصلية عن المستلمين الذين أُلحقوا لاحقًا.",
                max_length=20,
                verbose_name="مصدر الإضافة",
            ),
        ),
    ]
