# Generated by Django 5.2.17 on 2026-08-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0126_school_identity_uniqueness"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teacher",
            name="uniq_teacher_email_ci",
        ),
    ]
