# Generated by Django 5.2.17 on 2026-08-27 12:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_lab_departments(apps, schema_editor):
    Department = apps.get_model("reports", "Department")
    DepartmentMembership = apps.get_model("reports", "DepartmentMembership")
    LabAsset = apps.get_model("reports", "LabAsset")
    LabExperiment = apps.get_model("reports", "LabExperiment")

    school_departments = {}
    member_departments = {}

    def department_for(school_id, user_id):
        school_ids = school_departments.get(school_id)
        if school_ids is None:
            school_ids = tuple(
                Department.objects.filter(school_id=school_id, is_active=True)
                .order_by("id")
                .values_list("id", flat=True)
            )
            school_departments[school_id] = school_ids

        if user_id:
            key = (school_id, user_id)
            member_ids = member_departments.get(key)
            if member_ids is None:
                member_ids = tuple(
                    DepartmentMembership.objects.filter(
                        teacher_id=user_id,
                        department_id__in=school_ids,
                    )
                    .order_by("department_id")
                    .values_list("department_id", flat=True)
                    .distinct()
                )
                member_departments[key] = member_ids
            if len(member_ids) == 1:
                return member_ids[0]
        return school_ids[0] if len(school_ids) == 1 else None

    for asset in LabAsset.objects.filter(department__isnull=True).iterator():
        department_id = department_for(
            asset.school_id, asset.recorded_by_id or asset.custodian_id
        )
        if department_id:
            LabAsset.objects.filter(pk=asset.pk).update(department_id=department_id)

    for experiment in LabExperiment.objects.filter(department__isnull=True).iterator():
        department_id = department_for(experiment.school_id, experiment.recorder_id)
        if department_id:
            LabExperiment.objects.filter(pk=experiment.pk).update(
                department_id=department_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0127_circular_recipient_audit"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="labasset",
            name="reports_lab_school__e95916_idx",
        ),
        migrations.RemoveIndex(
            model_name="labasset",
            name="reports_lab_school__dcfe53_idx",
        ),
        migrations.RemoveIndex(
            model_name="labexperiment",
            name="reports_lab_school__cb5ef6_idx",
        ),
        migrations.RemoveIndex(
            model_name="labexperiment",
            name="reports_lab_school__426854_idx",
        ),
        migrations.AddField(
            model_name="labasset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="يفصل عهدة مختبر العلوم عن عهدة مختبر الحاسب الآلي.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_assets",
                to="reports.department",
                verbose_name="المختبر / القسم",
            ),
        ),
        migrations.AddField(
            model_name="labexperiment",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="يفصل تجارب مختبر العلوم عن تجارب مختبر الحاسب الآلي.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_experiments",
                to="reports.department",
                verbose_name="المختبر / القسم",
            ),
        ),
        migrations.RunPython(backfill_lab_departments, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="labasset",
            index=models.Index(
                fields=["school", "department", "condition"],
                name="reports_lab_school__46c562_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labasset",
            index=models.Index(
                fields=["school", "department", "category"],
                name="reports_lab_school__ba14a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labexperiment",
            index=models.Index(
                fields=["school", "department", "-experiment_date"],
                name="reports_lab_school__85b91f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labexperiment",
            index=models.Index(
                fields=["school", "department", "approval_state"],
                name="reports_lab_school__788f9b_idx",
            ),
        ),
    ]
