# Generated by Django 5.2 on 2026-08-27
from django.db import migrations, models


def _infer(name="", slug=""):
    text = f"{name or ''} {slug or ''}".strip().lower()
    if any(token in text for token in ("حاسب", "الحاسب", "computer", "computing", "it-lab")):
        return "computer"
    if any(token in text for token in ("علوم", "العلوم", "science")):
        return "science"
    return ""


def copy_legacy_lab_assignments(apps, schema_editor):
    LabAsset = apps.get_model("reports", "LabAsset")
    LabExperiment = apps.get_model("reports", "LabExperiment")
    SchoolMembership = apps.get_model("reports", "SchoolMembership")
    DepartmentMembership = apps.get_model("reports", "DepartmentMembership")

    for model in (LabAsset, LabExperiment):
        for row in model.objects.select_related("department").exclude(department=None).iterator():
            kind = _infer(row.department.name, row.department.slug)
            if kind:
                model.objects.filter(pk=row.pk).update(lab_kind=kind)

    memberships = SchoolMembership.objects.filter(job_title="lab_tech")
    for membership in memberships.iterator():
        kinds = {
            _infer(name, slug)
            for name, slug in DepartmentMembership.objects.filter(
                teacher_id=membership.teacher_id,
                department__school_id=membership.school_id,
                department__is_active=True,
            ).values_list("department__name", "department__slug")
        }
        kinds.discard("")
        if len(kinds) == 1:
            memberships.filter(pk=membership.pk).update(lab_kind=kinds.pop())


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0128_remove_labasset_reports_lab_school__e95916_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labasset",
            name="lab_kind",
            field=models.CharField(
                blank=True,
                choices=[("science", "مختبر العلوم"), ("computer", "مختبر الحاسب الآلي")],
                db_index=True,
                default="",
                help_text="مختبر العلوم أو مختبر الحاسب الآلي، مستقل عن أقسام التقارير.",
                max_length=16,
                verbose_name="المختبر",
            ),
        ),
        migrations.AddField(
            model_name="labexperiment",
            name="lab_kind",
            field=models.CharField(
                blank=True,
                choices=[("science", "مختبر العلوم"), ("computer", "مختبر الحاسب الآلي")],
                db_index=True,
                default="",
                help_text="مختبر العلوم أو مختبر الحاسب الآلي، مستقل عن أقسام التقارير.",
                max_length=16,
                verbose_name="المختبر",
            ),
        ),
        migrations.AddField(
            model_name="schoolmembership",
            name="lab_kind",
            field=models.CharField(
                blank=True,
                choices=[("science", "مختبر العلوم"), ("computer", "مختبر الحاسب الآلي")],
                default="",
                help_text="يُستخدم لمحضر المختبر فقط، وهو مستقل عن أقسام التقارير.",
                max_length=16,
                verbose_name="المختبر",
            ),
        ),
        migrations.RunPython(copy_legacy_lab_assignments, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="labasset",
            index=models.Index(fields=["school", "lab_kind", "condition"], name="reports_lab_school__85f3f2_idx"),
        ),
        migrations.AddIndex(
            model_name="labasset",
            index=models.Index(fields=["school", "lab_kind", "category"], name="reports_lab_school__6ee0b8_idx"),
        ),
        migrations.AddIndex(
            model_name="labexperiment",
            index=models.Index(fields=["school", "lab_kind", "-experiment_date"], name="reports_lab_school__7142fd_idx"),
        ),
        migrations.AddIndex(
            model_name="labexperiment",
            index=models.Index(fields=["school", "lab_kind", "approval_state"], name="reports_lab_school__21fb7c_idx"),
        ),
    ]
