# Generated by Django 4.2.27 on 2026-05-10 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0052_add_notification_is_broadcast"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolYearResetJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("previewed", "تمت المعاينة"),
                            ("running", "قيد التنفيذ"),
                            ("completed", "مكتملة"),
                            ("partial", "مكتملة جزئياً"),
                            ("failed", "فشلت"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "include_reports",
                    models.BooleanField(default=True, verbose_name="حذف التقارير"),
                ),
                (
                    "include_tickets",
                    models.BooleanField(
                        default=True, verbose_name="حذف الطلبات/التذاكر"
                    ),
                ),
                (
                    "include_achievements",
                    models.BooleanField(default=True, verbose_name="حذف ملفات الإنجاز"),
                ),
                (
                    "include_notifications",
                    models.BooleanField(
                        default=True, verbose_name="حذف التعاميم والإشعارات"
                    ),
                ),
                (
                    "include_share_links",
                    models.BooleanField(
                        default=True, verbose_name="حذف روابط المشاركة"
                    ),
                ),
                (
                    "delete_files",
                    models.BooleanField(
                        default=False, verbose_name="حذف المرفقات من التخزين"
                    ),
                ),
                (
                    "dry_run_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ملخص المعاينة"
                    ),
                ),
                (
                    "execution_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ملخص التنفيذ"
                    ),
                ),
                (
                    "file_manifest",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Manifest الملفات"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="بدأت في"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انتهت في"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="رسالة الخطأ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أنشئت في"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_year_reset_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئت بواسطة",
                    ),
                ),
                (
                    "schools",
                    models.ManyToManyField(
                        blank=True,
                        related_name="year_reset_jobs",
                        to="reports.school",
                        verbose_name="المدارس المستهدفة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية تهيئة عام دراسي",
                "verbose_name_plural": "عمليات تهيئة العام الدراسي",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
