# Generated by Django 5.2.16 on 2026-08-20 23:15

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("provider", models.CharField(default="hetzner", max_length=40)),
                (
                    "provider_server_id",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("public_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("region", models.CharField(blank=True, default="", max_length=80)),
                (
                    "server_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "سليم"),
                            ("degraded", "متدهور"),
                            ("down", "متوقف"),
                            ("unknown", "غير معروف"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "cpu_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "memory_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "disk_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ManagedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("base_url", models.URLField(max_length=300)),
                ("health_path", models.CharField(default="/healthz/", max_length=160)),
                ("expected_status", models.PositiveSmallIntegerField(default=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "سليم"),
                            ("degraded", "متدهور"),
                            ("down", "متوقف"),
                            ("maintenance", "صيانة"),
                            ("unknown", "غير معروف"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("alerts_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="operations.managedserver",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ManagedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("service_key", models.SlugField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("web", "تطبيق ويب"),
                            ("database", "قاعدة بيانات"),
                            ("cache", "ذاكرة مؤقتة"),
                            ("worker", "عامل خلفي"),
                            ("proxy", "وكيل عكسي"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "سليم"),
                            ("degraded", "متدهور"),
                            ("down", "متوقف"),
                            ("maintenance", "صيانة"),
                            ("unknown", "غير معروف"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("restart_allowed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="operations.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ("project", "kind", "name"),
            },
        ),
        migrations.CreateModel(
            name="MobileAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_mobile_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=160)),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("platform", models.CharField(default="android", max_length=24)),
                ("fcm_token", models.TextField(blank=True, default="")),
                ("alerts_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check_now", "فحص الآن"),
                            ("restart_service", "إعادة تشغيل خدمة"),
                            ("reload_proxy", "إعادة تحميل الوكيل"),
                            ("create_backup", "إنشاء نسخة احتياطية"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "في الانتظار"),
                            ("running", "قيد التنفيذ"),
                            ("succeeded", "نجحت"),
                            ("failed", "فشلت"),
                            ("rejected", "مرفوضة"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        default=operations.models._action_request_id,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "result_summary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="operations.managedproject",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="operations.managedservice",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ServerMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "memory_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "disk_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "redis_memory_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("queue_lengths", models.JSONField(blank=True, default=dict)),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="operations.managedserver",
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ok", models.BooleanField(db_index=True)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=60)),
                (
                    "response_summary",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="operations.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-checked_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["project", "-checked_at"],
                        name="operations__project_87842a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedupe_key", models.CharField(db_index=True, max_length=180)),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "معلومة"),
                            ("warning", "تحذير"),
                            ("critical", "حرج"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوحة"),
                            ("acknowledged", "تمت رؤيتها"),
                            ("resolved", "محلولة"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_operations_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="operations.managedproject",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="operations.managedserver",
                    ),
                ),
            ],
            options={
                "ordering": ("-opened_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["status", "severity", "-opened_at"],
                        name="operations__status_d0f312_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="managedservice",
            constraint=models.UniqueConstraint(
                fields=("project", "service_key"),
                name="operations_unique_project_service",
            ),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(
                fields=["is_active", "alerts_enabled"],
                name="operations__is_acti_57a0a6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobiledevice",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"), name="operations_unique_user_device"
            ),
        ),
        migrations.AddIndex(
            model_name="servermetricsnapshot",
            index=models.Index(
                fields=["server", "-captured_at"], name="operations__server__cf1732_idx"
            ),
        ),
    ]
