# Generated by Django 5.2.17 on 2026-08-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedproject",
            name="deploy_branch",
            field=models.CharField(blank=True, default="main", max_length=80),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="deploy_container",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="deploy_workflow",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="deployed_image",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="deployed_sha",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="deployment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="repository",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
